### ISSUE TITLE
Taking screenshot of one display.

### ISSUE THREAD

**Issue by ugnmura** [neXromancers/shotgun#30]
How do I make shotgun screenshot a single display?

**Comment by 9ary** [comment]
There is currently no option to do it directly, but you can pass a region with `-g`. It would be nice to add something like this though.

**Comment by ugnmura** [comment]
Maybe there could be some kind of flag that selects the current display and creates a screenshot.

**Comment by 9ary** [comment]
Yeah that's what I'm thinking. Unfortunately I can't work on shotgun anymore so someone else will have to contribute this. It shouldn't be too difficult though, shotgun isn't too complicated and we already handle listing monitors for another feature, so there's example code to look at.

**Comment by ugnmura** [comment]
I'm not really familiar with Rust but I can give it a try, since all programming languages work the same anyways. A proper review would be nice, since it probably won't be the best code.

**Comment by 9ary** [comment]
I'll be happy to review the code and we have other people who can help.
