### ISSUE TITLE
Casting a negative number to u32

### ISSUE THREAD

**Issue by dobryak** [neXromancers/shotgun#33]
Hello.
The result of this subtraction can be negative, that in turn leads to large values in sub.x and sub.y since they are casted to u32.
Also, this will cause u32 overflow in the .copy_from method.
https://github.com/neXromancers/shotgun/blob/1e5f5d7f75cc63d70af8f167380f85a116410baf/src/main.rs#L207-L208

**Comment by 9ary** [comment]
Good catch. I see what's going on now. Recent changes turned this:
https://github.com/neXromancers/shotgun/blob/2fc0d2ea8b522e47278fe02713cc546f62895c5c/src/main.rs#L143
into
https://github.com/neXromancers/shotgun/blob/1e5f5d7f75cc63d70af8f167380f85a116410baf/src/main.rs#L193-L197

This is a bug.
