### ISSUE TITLE
How can I specify which directory the screenshots will be stored?

### ISSUE THREAD

**Issue by AndyNotfound** [neXromancers/shotgun#34]
Hi, first of all I love your work, It's a lot faster. I've been wondering is there any way to make the screenshots stored on a specific directory?

**Comment by 9ary** [comment]
Thanks!

You can either pass a path as the file name (full path including a file name, not just a directory), or change the working directory (with cd) before calling shotgun.

I'm closing this issue because it's a question.

**Comment by AndyNotfound** [comment]
thanks for your fast response
